db_uri: mongodb://127.0.0.1/open5gs
logger:
  level: info
global:
  max:
    ue: 32
hss:
  freeDiameter: /opt/open5gs/etc/diameter/hss/hss.conf
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
